name: fonnx_example
description: Demonstrates how to use the fonnx plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fonnx:
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  cupertino_icons: ^1.0.2
  ffi: ^2.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  libmonet:
    git:
      url: https://github.com/Telosnex/libmonet.git
      ref: main
  record: ^5.0.4
  audioplayers: ^5.2.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/miniLmL6V2/miniLmL6V2.onnx
    - assets/models/msmarcoMiniLmL6V3/msmarcoMiniLmL6V3.onnx
    - assets/models/sileroVad/silero_vad.onnx
    - assets/models/whisper/whisper_tiny.onnx
    - assets/text_sample.txt
    - assets/audio_sample.wav
    - assets/audio_sample_16khz.wav
    - assets/silence_16khz.wav