// Generated by native_prebuilt:runtime_release. Do not edit.
// Release: https://github.com/Telosnex/fonnx/releases/tag/runtime-ccbd3cc9e0793906

import 'package:native_prebuilt/runtime.dart';

/// Runtime files of this package, by file name.
const nativePrebuiltRuntimeFiles = <String, RuntimeFile>{
  'bpe_decoder.onnx': RuntimeFile(
    name: 'bpe_decoder.onnx',
    sha256: '80525e3754c09e2f33c144388520b0050a7a2f414fb951c3d0bf7425aeb108ab',
    bytes: 375,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/bpe_decoder.onnx.gz',
    downloadSha256:
        '3e5e11d4e78b063446a0cd3cfb9faa303b5a0e89ebd7b6dfe1137e2a38ce04ad',
  ),
  'decoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx': RuntimeFile(
    name: 'decoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx',
    sha256: 'e40ff43297abe815e8898494c17e71bba2152d9d40fa3eb803f75d0f7533329a',
    bytes: 277985,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/decoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx.gz',
    downloadSha256:
        '79140a63486c42213dec54221437a9b15a223cfbe88fee3074c5884779447d36',
  ),
  'encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx': RuntimeFile(
    name: 'encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx',
    sha256: '1e721676515bcd42a186979733981213c66c80db680e1cc582dfedf3be76e678',
    bytes: 4807159,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx.gz',
    downloadSha256:
        '716e0aedf1bb658cea0a6fa1d57bf8f2a403e2f94a25273e18a15c032ba9e5fb',
  ),
  'futo_swipe_context_lm_hungry_jellyfish.onnx': RuntimeFile(
    name: 'futo_swipe_context_lm_hungry_jellyfish.onnx',
    sha256: '95722c67e2efde6cd925ddf57a0d44bf879824e53b7db45f32572bff97276979',
    bytes: 5955586,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/futo_swipe_context_lm_hungry_jellyfish.onnx.gz',
    downloadSha256:
        '71ed562168726105f0e10efe7f99995231482af798ce89d494812b45be9c3c37',
  ),
  'futo_swipe_decoder_magic_macaw.onnx': RuntimeFile(
    name: 'futo_swipe_decoder_magic_macaw.onnx',
    sha256: '16e478c542406f4c8a43a16a0a68b83a8f73b516975d66e691a1e1b46bd6dadf',
    bytes: 1228537,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/futo_swipe_decoder_magic_macaw.onnx.gz',
    downloadSha256:
        '67058e3df54da6e468c7833cdd3c804ba55a9a9d734f453a5e5f36b146c4aa6d',
  ),
  'futo_swipe_embeddings_hungry_jellyfish.onnx': RuntimeFile(
    name: 'futo_swipe_embeddings_hungry_jellyfish.onnx',
    sha256: 'd64902693fec59fb99a1ba986e9fd0668147d5e1e3b3b23cb91e100e2a5d71a1',
    bytes: 4456995,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/futo_swipe_embeddings_hungry_jellyfish.onnx.gz',
    downloadSha256:
        '510048e8d1af80c99d0c5bb331ce49614df49253447ce8a3b4860120a7510051',
  ),
  'futo_swipe_encoder_honorable_sturgeon.onnx': RuntimeFile(
    name: 'futo_swipe_encoder_honorable_sturgeon.onnx',
    sha256: 'e60b80b77c28e7bd426fa400435584991614d44ce4ba61eba408d8eb81f5f63b',
    bytes: 2591063,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/futo_swipe_encoder_honorable_sturgeon.onnx.gz',
    downloadSha256:
        '2675dab7d2758538d26c9b36891eb947df984de7e8b08b616d77e51bbb589b1c',
  ),
  'joiner-epoch-12-avg-2-chunk-16-left-64.int8.onnx': RuntimeFile(
    name: 'joiner-epoch-12-avg-2-chunk-16-left-64.int8.onnx',
    sha256: 'eae9da0c7e1e6c6a3f4cc42d167899c388f6c6701b94cb96320e4f55df79624c',
    bytes: 163380,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/joiner-epoch-12-avg-2-chunk-16-left-64.int8.onnx.gz',
    downloadSha256:
        '15caf8d109bc494a1e336e3c686319f94349006c99ab3467e543d7887eb71e47',
  ),
  'magika.onnx': RuntimeFile(
    name: 'magika.onnx',
    sha256: '71892ac28ffe028b9512561584970417f8cee1f2fbb7624634f4032cb92a0a5a',
    bytes: 1055295,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/magika.onnx.gz',
    downloadSha256:
        'efa20ab5edff7e80ebe6d1c103d473183ee986cd88da35153710eace3274b573',
  ),
  'miniLmL6V2.onnx': RuntimeFile(
    name: 'miniLmL6V2.onnx',
    sha256: '3a4ae4f8f00d87c93b04aca370ed1c5e94f80a32912f2cf5516291703353bf84',
    bytes: 22887725,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/miniLmL6V2.onnx.gz',
    downloadSha256:
        'e70ec469507d91db7e846480f4c89f9f3cd5fee51ac649fb1843da47ad4ccc56',
  ),
  'msmarcoMiniLmL6V3.onnx': RuntimeFile(
    name: 'msmarcoMiniLmL6V3.onnx',
    sha256: 'e80318c560513a6dcf32e4404d12ef6676af9f85ffee63e1e8ce249651e4f794',
    bytes: 22913492,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/msmarcoMiniLmL6V3.onnx.gz',
    downloadSha256:
        '642c1e25c6e35e8d141c0993fa0c3b2b76f78572378690b84df3f8865a40d222',
  ),
  'potion32m.onnx': RuntimeFile(
    name: 'potion32m.onnx',
    sha256: 'e82f46335878dd5d72f9544a2a7c61061659c6273ceb8815e10ff952c2e07457',
    bytes: 129214550,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/potion32m.onnx.gz',
    downloadSha256:
        '870bc8cb71e6c98f322e2440529686cd6a989d469f8559b1a46e13be2b18f89b',
  ),
  'potion8m.onnx': RuntimeFile(
    name: 'potion8m.onnx',
    sha256: 'da4c828fe012ec97f053278f363645b52c3815ec9a1d13d695ac901398c10f2e',
    bytes: 30240854,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/potion8m.onnx.gz',
    downloadSha256:
        '29734413f6ce507cad33434fd0eed274a7cb07a69e6b6c7f47715772258fbc69',
  ),
  'pyannote_seg3.onnx': RuntimeFile(
    name: 'pyannote_seg3.onnx',
    sha256: '057ee564753071c0b09b5b611648b50ac188d50846bff5f01e9f7bbf1591ea25',
    bytes: 5986908,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/pyannote_seg3.onnx.gz',
    downloadSha256:
        '23ae1a1effa6ab51598c075e2407302657a64e4343a621ca094c7f4385f322c1',
  ),
  'silero_vad_v6.2.1.onnx': RuntimeFile(
    name: 'silero_vad_v6.2.1.onnx',
    sha256: '1a153a22f4509e292a94e67d6f9b85e8deb25b4988682b7e174c65279d8788e3',
    bytes: 2327524,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/silero_vad_v6.2.1.onnx.gz',
    downloadSha256:
        '7114c6508d90feb8e32c6176155709a48a6136f8efa8dfff567514f8ec3eda39',
  ),
  'whisper_tiny.onnx': RuntimeFile(
    name: 'whisper_tiny.onnx',
    sha256: 'f3b7c806032cf080f185330ad4c593e8d1ed97f61ce354f844453c7173933d14',
    bytes: 74823452,
    url:
        'https://github.com/Telosnex/fonnx/releases/download/runtime-ccbd3cc9e0793906/whisper_tiny.onnx.gz',
    downloadSha256:
        'a722785ef35c856f5bcd4fa850f2535217c323f84d8baa9ab2013b2089bf4f6f',
  ),
};
