output: "../lib/onnx/ort_ffi_bindings.dart"
ignore-source-errors: true
headers:
  entry-points:
    - "../onnx_runtime/headers/**.h"
ffi-native:
preamble: |
  // ignore_for_file: type=lint, unused_field, unused_element
